apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-catalog
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/aks-on-demand-portal.git'
    path: 'namespace-catalog'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'namespace-portal-system'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
