name: Terraform CI/CD

on:
  pull_request:
    paths:
      - 'terraform/**'
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID:     ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:     ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format & Validate
        working-directory: ./terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -out tfplan

      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
